Algoritmo "Area_do_retângulo"
// Descrição   : Calcular a area do retângulo
// Autor(a)    : João Marques
// Data atual  : 14/09/2017
Var
    comprimento,largura,area : real
Inicio
    escreva("Qual o comprimento do retângulo?")
    leia (comprimento)
    escreva("Qual a Largura do retângulo?")
    leia (largura)
    area <- (comprimento) * (largura)
    escreva("A area do retângulo é",area)
Fimalgoritmo