Algoritmo "idade nadador"
// Autor(a)    : Joao Marques
// Data atual  : 28/09/2017
Var
idade : real  flag,X:logico
Inicio
X:=verdadeiro
flag <- x
enquanto flag faca
x:=verdadeiro
limpatela
escreva("insira a idade")
leia (idade)
escolha idade
caso 5 ate 7
escreva ("infantil a")
caso 8 ate 10
escreva ("infantil b")
caso 11 ate 13
escreva ("juvenil a")
caso 14 ate 17
escreva ("juvenil b")
caso 18 ate 1000
escreva ("senior")
fimescolha
leia(X)
fimenquanto
Fimalgoritmo